language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t chronicideas/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true chronicideas/docker-react npm run test